//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public int Id { get; set; }
        public int netMonthIncome { get; set; }
        public int pension { get; set; }
        public int savingsIncome { get; set; }
        public int otherIncome { get; set; }
        public int totalIncome { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
